version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db

  postgres:
    image: postgres:14.4-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
